version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.favicon
    - Resume_Aug2018_SteveBarron.pdf
    - styles/main.css
    - images/*
